
name = "spetech-lnf"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB" # Nama variabel yang dipanggil di API (functions)
database_name = "spetech_db"
database_id = "788d2f09-5499-4224-8c28-586e066e7f2c"
